### ISSUE TITLE
Pretrained checkpoint of RN18 on cifar-10, 100

### ISSUE THREAD

**Issue by priyamdey** [rdangovs/essl#1]
Hi there! Thanks for sharing the codebase. Can you please provide the pretrained checkpoints of RN18 on cifar10 & cifar100 for the 800ep?

Thanks

**Comment by rdangovs** [comment]
Hello! Were you able to train these checkpoints by yourself? If not, I can share some of the checkpoints I can find in my archive.

**Comment by priyamdey** [comment]
Hey, yes we were able to train these eventually. Will close this thread. I think moving ahead, it will be beneficial for the community as well if you can attach some of these checkpoints in the readme (if not done already).
Thanks
